import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const BIN = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "bin", "aief.js");
const POSIX = process.platform !== "win32";

function makeProject(files = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "aief-cli-"));
  for (const [name, content] of Object.entries(files)) {
    const full = path.join(dir, name);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, "utf8");
  }
  return dir;
}

function aief(cwd, args, env = {}) {
  const result = spawnSync(process.execPath, [BIN, ...args], {
    cwd,
    encoding: "utf8",
    env: { ...process.env, ...env }
  });
  return { status: result.status, out: `${result.stdout}${result.stderr}` };
}

test("new-change assigns sequential ids", () => {
  const dir = makeProject();
  aief(dir, ["new-change", "First Thing"]);
  aief(dir, ["new-change", "second-thing"]);
  const changes = fs.readdirSync(path.join(dir, "changes")).sort();
  assert.deepEqual(changes, ["0001-first-thing", "0002-second-thing"]);
});

test("adopt does not collide with existing change ids", () => {
  const dir = makeProject({ "changes/0001-existing/change.md": "# Change" });
  const { status, out } = aief(dir, ["adopt"]);
  assert.equal(status, 0);
  assert.match(out, /0002-adopt-aief/);
  const changes = fs.readdirSync(path.join(dir, "changes")).sort();
  assert.deepEqual(changes, ["0001-existing", "0002-adopt-aief"]);
});

test("adopt is idempotent", () => {
  const dir = makeProject();
  aief(dir, ["adopt"]);
  const { out } = aief(dir, ["adopt"]);
  assert.match(out, /Adoption Change already exists/);
  const adoptDirs = fs.readdirSync(path.join(dir, "changes")).filter((n) => n.includes("adopt-aief"));
  assert.equal(adoptDirs.length, 1);
});

test("adopt does not touch application files", () => {
  const dir = makeProject({ "src/app.js": "console.log('app');" });
  aief(dir, ["adopt"]);
  assert.equal(fs.readFileSync(path.join(dir, "src", "app.js"), "utf8"), "console.log('app');");
});

test("adopt creates starter standards and never overwrites existing ones", () => {
  const dir = makeProject({
    "package.json": JSON.stringify({ dependencies: { react: "18.0.0" } }),
    "knowledge/standards/base-standards.md": "MY CUSTOM RULES"
  });
  const { out } = aief(dir, ["adopt"]);
  assert.match(out, /Created knowledge\/standards\/frontend-standards\.md/);
  assert.equal(fs.readFileSync(path.join(dir, "knowledge", "standards", "base-standards.md"), "utf8"), "MY CUSTOM RULES");
  const files = fs.readdirSync(path.join(dir, "knowledge", "standards"));
  assert.ok(files.includes("frontend-standards.md"), "frontend standards expected for a React project");
  assert.ok(!files.includes("backend-standards.md"), "no backend standards for a frontend-only project");
});

test("adopt on an unknown stack creates only the base standards", () => {
  const dir = makeProject({ "README.md": "A plain library." });
  aief(dir, ["adopt"]);
  const files = fs.readdirSync(path.join(dir, "knowledge", "standards")).sort();
  assert.deepEqual(files, ["base-standards.md", "documentation-standards.md", "security-standards.md", "testing-standards.md"]);
});

test("adopt documents its own adoption Change automatically (no placeholder evidence)", () => {
  const dir = makeProject({ "README.md": "Multi-tenant SaaS." });
  const { out } = aief(dir, ["adopt"]);
  assert.match(out, /evidence generated automatically/);
  const ev = fs.readFileSync(path.join(dir, "changes", "0001-adopt-aief", "evidence.md"), "utf8");
  assert.match(ev, /Generated by AIEF during adoption/);
  assert.doesNotMatch(ev, /^Pending\.$/m);
  assert.match(ev, /No functional code changed/);
  assert.match(ev, /knowledge\/standards\/base-standards\.md/);
  assert.match(ev, /multitenant/);
  const verify = aief(dir, ["verify"]);
  assert.doesNotMatch(verify.out, /0001-adopt-aief — in progress/);
  assert.match(verify.out, /✓ changes\/0001-adopt-aief/);
});

test("adopt documents recommended Skills in knowledge/skills.md", () => {
  const dir = makeProject({ "README.md": "Multi-tenant SaaS." });
  const { out } = aief(dir, ["adopt"]);
  assert.match(out, /Skills documented: knowledge\/skills\.md/);
  const doc = fs.readFileSync(path.join(dir, "knowledge", "skills.md"), "utf8");
  assert.match(doc, /Generated by AIEF during adoption/);
  assert.match(doc, /not commands and are never executed/);
  assert.match(doc, /Multitenant SaaS Architect/);
  assert.match(doc, /\*\*Why recommended:\*\* .*tenant/);
  assert.match(doc, /knowledge\/standards\/security-standards\.md/);
  assert.match(doc, /\*\*Evidence expectations:\*\*/);
});

test("adopt never overwrites an existing knowledge/skills.md", () => {
  const dir = makeProject({ "README.md": "Multi-tenant SaaS.", "knowledge/skills.md": "MY PROJECT NOTES" });
  const { out } = aief(dir, ["adopt"]);
  assert.match(out, /Skills documentation already exists: knowledge\/skills\.md/);
  assert.equal(fs.readFileSync(path.join(dir, "knowledge", "skills.md"), "utf8"), "MY PROJECT NOTES");
});

test("prompt references knowledge/skills.md and keeps Skills as context, not commands", () => {
  const dir = makeProject({ "README.md": "Multi-tenant SaaS." });
  aief(dir, ["adopt"]);
  aief(dir, ["analyze"]);
  const { out } = aief(dir, ["prompt", "--profile", "architect"]);
  assert.match(out, /- knowledge\/skills\.md/);
  assert.match(out, /included as context, not executed/);
  const changeMd = fs.readFileSync(path.join(dir, "changes", "0002-analyze-current-architecture", "change.md"), "utf8");
  assert.match(changeMd, /Full Skill knowledge: knowledge\/skills\.md/);
});

test("verify guides the next step after PASS and after FAIL", () => {
  const dir = makeProject({ "README.md": "x" });
  aief(dir, ["adopt"]);
  const pass = aief(dir, ["verify"]);
  assert.match(pass.out, /Next:/);
  assert.match(pass.out, /aief close --yes \(active Change 0001-adopt-aief looks ready\)/);
  fs.rmSync(path.join(dir, "changes", "0001-adopt-aief", "spec.md"));
  const fail = aief(dir, ["verify"]);
  assert.equal(fail.status, 1);
  assert.match(fail.out, /fix the issues above/);
});

test("doctor reports OpenSpec as optional; status has no mandatory warnings for optional artifacts", () => {
  const dir = makeProject({ "README.md": "x" });
  aief(dir, ["adopt"]);
  const d = aief(dir, ["doctor"], { PATH: path.dirname(process.execPath) });
  assert.match(d.out, /openspec: not detected \(optional\)/);
  assert.doesNotMatch(d.out, /! Navigator/);
  assert.doesNotMatch(d.out, /! Profiles/);
  assert.doesNotMatch(d.out, /! OpenSpec adapter/);
  assert.doesNotMatch(d.out, /! Specboot adapter/);
  assert.match(d.out, /· Navigator: not present \(optional\)/);
});

test("analyze seeds the Change with real detections, marked as inference", () => {
  const dir = makeProject({ "README.md": "Multi-tenant SaaS." });
  aief(dir, ["adopt"]);
  aief(dir, ["analyze"]);
  const changeMd = fs.readFileSync(path.join(dir, "changes", "0002-analyze-current-architecture", "change.md"), "utf8");
  assert.match(changeMd, /## Detected Context/);
  assert.match(changeMd, /confirm or discard/);
  assert.match(changeMd, /multitenant \(weak\)/);
  assert.match(changeMd, /inferred from multitenant-saas-architect/);
  assert.match(changeMd, /knowledge\/standards\/security-standards\.md/);
});

test("prompt includes standards and Skill context honestly", () => {
  const dir = makeProject({ "README.md": "Multi-tenant SaaS." });
  aief(dir, ["adopt"]);
  aief(dir, ["analyze"]);
  const { out } = aief(dir, ["prompt", "--profile", "architect"]);
  assert.match(out, /Project standards to follow/);
  assert.match(out, /knowledge\/standards\/base-standards\.md/);
  assert.match(out, /included as context, not executed/);
  assert.match(out, /Multitenant SaaS Architect/);
  assert.match(out, /Watch out for: queries missing the tenant filter/);
});

test("prompt is honest when a recommended Skill has no operational content", () => {
  const dir = makeProject({ "README.md": "A plain library." });
  aief(dir, ["new-change", "thing"]);
  const { out } = aief(dir, ["prompt"]);
  assert.match(out, /no operational content yet/);
});

test("verify passes right after adopt creates standards", () => {
  const dir = makeProject({ "README.md": "x" });
  aief(dir, ["adopt"]);
  const { status, out } = aief(dir, ["verify"]);
  assert.equal(status, 0);
  assert.match(out, /Result: PASS/);
});

test("doctor explains skill recommendations", () => {
  const dir = makeProject({ "README.md": "Multi-tenant SaaS platform." });
  const { status, out } = aief(dir, ["doctor"]);
  assert.equal(status, 0);
  assert.match(out, /multitenant-saas-architect/);
  assert.match(out, /because: .*tenant/i);
});

test("doctor does not recommend governance for generic prose", () => {
  const dir = makeProject({ "README.md": "We value maintainability and plain code." });
  const { out } = aief(dir, ["doctor"]);
  assert.doesNotMatch(out, /ai-workflow-governance/);
  assert.doesNotMatch(out, /multitenant-saas-architect/);
});

test("analyze creates an Analysis Change with the standard evidence structure", () => {
  const dir = makeProject();
  const { status } = aief(dir, ["analyze"]);
  assert.equal(status, 0);
  const changeDir = path.join(dir, "changes", "0001-analyze-current-architecture");
  assert.match(fs.readFileSync(path.join(changeDir, "change.md"), "utf8"), /## Type\n\nAnalysis/);
  const evidence = fs.readFileSync(path.join(changeDir, "evidence.md"), "utf8");
  for (const sectionName of ["Summary", "Activities Performed", "Verification", "Findings", "Risks", "Recommendations", "Artifacts Produced", "Lessons Learned", "Next Change"]) {
    assert.match(evidence, new RegExp(`## ${sectionName}`), `evidence.md must contain ${sectionName}`);
  }
});

test("prompt recognizes an Analysis Change even with CRLF line endings", () => {
  const dir = makeProject();
  aief(dir, ["analyze"]);
  const changeFile = path.join(dir, "changes", "0001-analyze-current-architecture", "change.md");
  fs.writeFileSync(changeFile, fs.readFileSync(changeFile, "utf8").replace(/\n/g, "\r\n"), "utf8");
  const { out } = aief(dir, ["prompt", "--profile", "architect"]);
  assert.match(out, /Do not modify application source code/);
});

test("prompt warns against overwriting when evidence has real content", () => {
  const dir = makeProject();
  aief(dir, ["new-change", "thing"]);
  fs.writeFileSync(path.join(dir, "changes", "0001-thing", "evidence.md"), "# Evidence\n\n## Summary\n\nReal validated findings.\n", "utf8");
  const { out } = aief(dir, ["prompt"]);
  assert.match(out, /evidence\.md already exists and has real content/);
  assert.match(out, /Do not overwrite it blindly/);
  assert.match(out, /report that the evidence was re-verified/);
});

test("prompt has no overwrite warning for placeholder or empty evidence", () => {
  const dir = makeProject();
  aief(dir, ["new-change", "thing"]);
  const fresh = aief(dir, ["prompt"]);
  assert.doesNotMatch(fresh.out, /Do not overwrite it blindly/);
  fs.writeFileSync(path.join(dir, "changes", "0001-thing", "evidence.md"), "", "utf8");
  const empty = aief(dir, ["prompt"]);
  assert.doesNotMatch(empty.out, /Do not overwrite it blindly/);
});

test("prompt separates project evidence from AIEF feedback and clarifies tasks ownership", () => {
  const dir = makeProject();
  aief(dir, ["analyze"]);
  const { out } = aief(dir, ["prompt"]);
  assert.match(out, /Where results belong/);
  assert.match(out, /Feedback about AIEF or the tooling goes in your response/);
  assert.match(out, /Do not mark tasks\.md items yourself unless the Change or the user explicitly asks/);
  assert.match(out, /tell the user which tasks appear complete/);
  assert.match(out, /complete or amend/);
});

test("prompt accepts the assistant as a positional argument for all four assistants", () => {
  const dir = makeProject({ "CLAUDE.md": "#c", "GEMINI.md": "#g", "CODEX.md": "#x", "CURSOR.md": "#u" });
  aief(dir, ["new-change", "thing"]);
  for (const [name, file] of [["gemini", "GEMINI.md"], ["claude", "CLAUDE.md"], ["codex", "CODEX.md"], ["cursor", "CURSOR.md"]]) {
    const r = aief(dir, ["prompt", name]);
    assert.equal(r.status, 0, `prompt ${name} must succeed`);
    assert.match(r.out, new RegExp(`- ${file}`), `prompt ${name} must include ${file}`);
  }
});

test("--assistant wins over the positional argument", () => {
  const dir = makeProject({ "GEMINI.md": "#g", "CODEX.md": "#x" });
  aief(dir, ["new-change", "thing"]);
  const r = aief(dir, ["prompt", "gemini", "--assistant", "codex"]);
  assert.equal(r.status, 0);
  assert.match(r.out, /- CODEX\.md/);
  assert.doesNotMatch(r.out, /- GEMINI\.md/);
});

test("unknown positional assistant fails with guidance — never a silent fallback", () => {
  const dir = makeProject({ "CLAUDE.md": "#c" });
  aief(dir, ["new-change", "thing"]);
  const r = aief(dir, ["prompt", "architect"]);
  assert.equal(r.status, 1);
  assert.match(r.out, /Unknown assistant "architect"/);
  assert.match(r.out, /- claude/);
  assert.match(r.out, /--profile architect/);
  assert.doesNotMatch(r.out, /Copy this prompt/);
});

test("prompt --assistant selects the matching instruction file", () => {
  const dir = makeProject({ "GEMINI.md": "# Gemini rules", "CLAUDE.md": "# Claude rules" });
  aief(dir, ["new-change", "thing"]);
  const gemini = aief(dir, ["prompt", "--assistant", "gemini"]);
  assert.match(gemini.out, /- GEMINI\.md/);
  assert.doesNotMatch(gemini.out, /- CLAUDE\.md/);
  const fallback = aief(dir, ["prompt"]);
  assert.match(fallback.out, /- CLAUDE\.md/);
  const unknown = aief(dir, ["prompt", "--assistant", "clippy"]);
  assert.match(unknown.out, /Unknown assistant "clippy"/);
});

test("verify fails when a change file is missing and stays calm about in-progress evidence", () => {
  const dir = makeProject({ "README.md": "x", "AGENTS.md": "x" });
  aief(dir, ["new-change", "thing"]);
  const pass = aief(dir, ["verify"]);
  assert.equal(pass.status, 0);
  assert.match(pass.out, /in progress \(evidence not completed yet; expected/);
  assert.doesNotMatch(pass.out, /✗/);
  fs.rmSync(path.join(dir, "changes", "0001-thing", "spec.md"));
  const fail = aief(dir, ["verify"]);
  assert.equal(fail.status, 1);
  assert.match(fail.out, /spec\.md missing/);
});

test("close refuses an incomplete Change and explains what is pending", () => {
  const dir = makeProject();
  aief(dir, ["new-change", "thing"]);
  const report = aief(dir, ["close"]);
  assert.equal(report.status, 0);
  assert.match(report.out, /evidence\.md has not been completed yet/);
  assert.match(report.out, /unchecked task/);
  const refused = aief(dir, ["close", "--yes"]);
  assert.equal(refused.status, 1);
  assert.match(refused.out, /Not closed/);
  assert.doesNotMatch(fs.readFileSync(path.join(dir, "changes", "0001-thing", "change.md"), "utf8"), /## Status/);
});

test("close --yes marks a ready Change as Closed; the Change stops being active", () => {
  const dir = makeProject();
  aief(dir, ["new-change", "thing"]);
  const changeDir = path.join(dir, "changes", "0001-thing");
  fs.writeFileSync(path.join(changeDir, "evidence.md"), "# Evidence\n\n## Summary\n\nReal work happened.\n", "utf8");
  fs.writeFileSync(path.join(changeDir, "tasks.md"), "# Tasks\n\n- [x] Everything done.\n", "utf8");
  const closed = aief(dir, ["close", "--yes"]);
  assert.equal(closed.status, 0);
  assert.match(closed.out, /✓ Closed changes\/0001-thing/);
  assert.match(fs.readFileSync(path.join(changeDir, "change.md"), "utf8"), /## Status\n\nClosed \(\d{4}-\d{2}-\d{2}\)/);
  const verify = aief(dir, ["verify"]);
  assert.match(verify.out, /0001-thing \(closed\)/);
  const noOpen = aief(dir, ["prompt"]);
  assert.equal(noOpen.status, 1);
  assert.match(noOpen.out, /No open Change found/);
  aief(dir, ["new-change", "second"]);
  const next = aief(dir, ["prompt"]);
  assert.equal(next.status, 0);
  assert.match(next.out, /0002-second/);
});

test("propose without OpenSpec falls back loudly to a local Change", () => {
  const dir = makeProject();
  const { status, out } = aief(dir, ["propose", "Add login"], { PATH: path.dirname(process.execPath) });
  assert.equal(status, 0);
  assert.match(out, /OpenSpec is not installed/);
  assert.ok(fs.existsSync(path.join(dir, "changes", "0001-add-login", "proposal.md")));
});

test("propose warns when OpenSpec lacks a propose command", { skip: !POSIX }, () => {
  const dir = makeProject();
  const fakeBin = path.join(dir, "fakebin");
  fs.mkdirSync(fakeBin);
  fs.writeFileSync(path.join(fakeBin, "openspec"), "#!/bin/sh\ncase \"$1\" in\n--version) echo 1.2.3 ;;\n--help) echo 'usage: openspec [validate]' ;;\n*) exit 1 ;;\nesac\n", { mode: 0o755 });
  const { out } = aief(dir, ["propose", "Add login"], { PATH: `${fakeBin}:${process.env.PATH}` });
  assert.match(out, /does not expose a "propose" command/);
  assert.match(out, /Falling back to local Change generation/);
});

test("propose reports delegation failure and falls back", { skip: !POSIX }, () => {
  const dir = makeProject();
  const fakeBin = path.join(dir, "fakebin");
  fs.mkdirSync(fakeBin);
  fs.writeFileSync(path.join(fakeBin, "openspec"), "#!/bin/sh\ncase \"$1\" in\n--version) echo 9.9.9 ;;\n--help) echo 'commands: propose validate' ;;\npropose) exit 7 ;;\n*) exit 1 ;;\nesac\n", { mode: 0o755 });
  const { out } = aief(dir, ["propose", "Add login"], { PATH: `${fakeBin}:${process.env.PATH}` });
  assert.match(out, /OpenSpec delegation failed \(exit code 7\)\. Falling back to local Change generation\./);
  assert.ok(fs.existsSync(path.join(dir, "changes", "0001-add-login", "proposal.md")));
});

test("close works when change.md prose merely mentions \"## Status\"", () => {
  const dir = makeProject();
  aief(dir, ["new-change", "thing"]);
  const changeDir = path.join(dir, "changes", "0001-thing");
  fs.appendFileSync(path.join(changeDir, "change.md"), "\nThis Change adds a `## Status` section to templates.\n");
  fs.writeFileSync(path.join(changeDir, "evidence.md"), "# Evidence\n\n## Summary\n\nDone.\n", "utf8");
  fs.writeFileSync(path.join(changeDir, "tasks.md"), "# Tasks\n\n- [x] Done.\n", "utf8");
  const closed = aief(dir, ["close", "--yes"]);
  assert.equal(closed.status, 0);
  assert.match(fs.readFileSync(path.join(changeDir, "change.md"), "utf8"), /\n## Status\n\nClosed \(\d{4}-\d{2}-\d{2}\)/);
  const verify = aief(dir, ["verify"]);
  assert.match(verify.out, /0001-thing \(closed\)/);
});

test("help covers every documented command with six fields", () => {
  const dir = makeProject();
  for (const command of ["doctor", "status", "adopt", "analyze", "new-change", "propose", "prompt", "verify", "close", "release", "init", "use-profile", "help", "explain"]) {
    const { status, out } = aief(dir, ["help", command]);
    assert.equal(status, 0, `help ${command} must exit 0`);
    for (const field of ["Purpose", "When to use it", "Reads", "Writes", "Example", "Next step"]) {
      assert.match(out, new RegExp(field), `help ${command} must include ${field}`);
    }
  }
});

test("--help and -h show usage and exit 0", () => {
  const dir = makeProject();
  for (const flag of ["--help", "-h"]) {
    const { status, out } = aief(dir, [flag]);
    assert.equal(status, 0, `${flag} must exit 0`);
    assert.match(out, /AIEF CLI/);
    assert.match(out, /Usage:/);
    assert.match(out, /aief doctor/);
    assert.match(out, /aief init/);
  }
});

test("--version prints the CLI version", () => {
  const dir = makeProject();
  const { status, out } = aief(dir, ["--version"]);
  assert.equal(status, 0);
  assert.match(out, /^aief \d+\.\d+\.\d+/);
});

test("doctor groups tools by level and never fails because of optional tools", () => {
  const dir = makeProject();
  const { out } = aief(dir, ["doctor"], { PATH: path.dirname(process.execPath) });
  assert.match(out, /Core \(required\):/);
  assert.match(out, /SDD \(recommended\):/);
  assert.match(out, /Build tools \(optional\):/);
  assert.match(out, /Assistants \(optional\):/);
  assert.match(out, /Summary:/);
  // With a stripped PATH the optional tools are absent — reported, not fatal.
  assert.match(out, /○ (java|docker|claude): not detected \(optional\)/);
});

test("doctor reports missing required tools in the summary", { skip: !POSIX }, () => {
  const dir = makeProject();
  const emptyBin = path.join(dir, "emptybin");
  fs.mkdirSync(emptyBin);
  const { status, out } = aief(dir, ["doctor"], { PATH: emptyBin });
  assert.equal(status, 1);
  assert.match(out, /✗ git: not found \(required\)/);
  assert.match(out, /Missing required tools: .*git/);
});

test("init without arguments initializes the current directory with visible structure only", () => {
  const dir = makeProject({ "src/app.js": "console.log('app');" });
  const { status, out } = aief(dir, ["init"], { PATH: path.dirname(process.execPath) });
  assert.equal(status, 0);
  assert.match(out, /AIEF Init/);
  assert.match(out, /never modifies application code/);
  assert.match(out, /Next steps:/);
  assert.match(out, /Install OpenSpec if missing: npm install -g @fission-ai\/openspec@latest/);
  assert.ok(fs.existsSync(path.join(dir, "AGENTS.md")));
  assert.ok(fs.existsSync(path.join(dir, "changes")));
  assert.ok(fs.existsSync(path.join(dir, "knowledge")));
  // ADR-009: no hidden state — init must never create a .aief/ directory.
  assert.ok(!fs.existsSync(path.join(dir, ".aief")));
  assert.equal(fs.readFileSync(path.join(dir, "src", "app.js"), "utf8"), "console.log('app');");
});

test("init without arguments is idempotent and reports what already exists", () => {
  const dir = makeProject();
  aief(dir, ["init"]);
  const { status, out } = aief(dir, ["init"]);
  assert.equal(status, 0);
  assert.match(out, /✓ AGENTS\.md/);
  assert.match(out, /✓ changes\//);
  assert.match(out, /Adoption Change already exists/);
});

test("init with a name still creates a new project skeleton", () => {
  const dir = makeProject();
  const { status, out } = aief(dir, ["init", "my-project"]);
  assert.equal(status, 0);
  assert.match(out, /Created AIEF project/);
  for (const entry of ["README.md", "AGENTS.md", "changes", "knowledge", "src", "tests"]) {
    assert.ok(fs.existsSync(path.join(dir, "my-project", entry)), `my-project/${entry} expected`);
  }
});

test("release reports honestly when notes already exist", () => {
  const dir = makeProject();
  const first = aief(dir, ["release", "0.9.0"]);
  assert.match(first.out, /Created release notes/);
  const second = aief(dir, ["release", "0.9.0"]);
  assert.match(second.out, /already exist/);
});
